### ISSUE TITLE
fabric-javaenv:arm64-1.4.1

### ISSUE THREAD

**Issue by AbelPelser** [Tunstad/Hyperprov#14]
Hi there,

In regards to compiling fabric-javaenv for arm64, you mention that you haven't managed to do so yet and that it might not be worth pursuing. Well, we've pushed through with it and managed to compile an image, which can be pulled from the Docker hub: `docker pull apelser/fabric-javaenv:arm64-1.4.1` . Also, here are the steps we took to compile it, which you can use to update [compiling.md](https://github.com/Tunstad/Hyperprov/blob/master/compiling.md).

Install dependencies:
- [ ] `sudo apt-get install autoconf automake libtool curl make g++ unzip maven ninja-build cmake perl libssl-dev libapr1-dev tar git openjdk-8-jdk -y`
Compile netty-tcnative:
- [ ] `git clone https://github.com/netty/netty-tcnative.git`
- [ ] `cd netty-tcnative`
- [ ] `git checkout netty-tcnative-parent-2.0.7.Final`
Apply [this patch](https://github.com/Tunstad/Hyperprov/files/3107297/netty-tcnative-fixes.patch.txt) (remove the .txt at the end)
- [ ] `git apply netty-tcnative-fixes.patch`
The CXFLAGS are only necessary certain versions of GCC
- [ ] `CXFLAGS="Wno-error=misleading-indentation" mvn clean install`
The jar we need is now at /path/to/netty-tcnative/boringssl-static/target/netty-tcnative-boringssl-static-2.0.7.Final-linux-aarch_64.jar

Compile protobuf:
- [ ] `git clone https://github.com/protocolbuffers/protobuf.git`
- [ ] `cd protobuf`
- [ ] `git checkout v3.0.0`
- [ ] `git submodule update --init --recursive`
Modify autogen.sh, change:
    `curl $curlopts -O https://googlemock.googlecode.com/files/gmock-1.7.0.zip`
    into:
    `curl $curlopts -O https://src.fedoraproject.org/repo/pkgs/gmock/gmock-1.7.0.zip/073b984d8798ea1594f5e44d85b20d66/gmock-1.7.0.zip`
- [ ] `./autogen.sh`
- [ ] `./configure --disable-shared`
On a Pi, ensure your memory/swap file is large enough before proceeding
- [ ] `make`
Recommended, but very (!) time-consuming on a Raspberry Pi 3B+ :
- [ ] `make check`
- [ ] `sudo make install`
Compile protoc-gen-grpc-java:
- [ ] `git clone https://github.com/grpc/grpc-java.git`
- [ ] `cd grpc-java`
- [ ] `git checkout v1.9.0`
- [ ] `cd compiler`
- [ ] `../gradlew java_pluginExecutable`
The executable can now be found under /path/to/grpc-java/compiler/build/exe/java_plugin/protoc-gen-grpc-java
Finally, to compile the docker image itself:
- [ ] `git clone https://github.com/hyperledger/fabric-chaincode-java.git`
- [ ] `cd fabric-chaincode-java`
- [ ] `git checkout v1.4.1`
Apply [this patch](https://github.com/Tunstad/Hyperprov/files/3111188/fabric-chaincode-java-fixes.patch.txt) (remove the .txt at the end)
- [ ] `git apply fabric-chaincode-java-fixes.patch`
Copy the aforementioned jar and `protoc-gen-grpc-java` to fabric-chaincode-java/fabric-chaincode-docker
- [ ] `cd fabric-chaincode-docker`
- [ ] `mkdir -p build/distributions/chaincode-java/shim-src`
- [ ] `mkdir -p build/distributions/chaincode-java/example-src/`
This `libs` directory is only used to store our jar and protoc-gen-grpc-java plugin
- [ ] `mkdir -p build/distributions/chaincode-java/libs/`
- [ ] `cp build.gradle build/distributions/chaincode-java/`
- [ ] `cp build.sh build/distributions/chaincode-java/`
- [ ] `cp start build/distributions/chaincode-java/`
- [ ] `cp protoc-gen-grpc-java build/distributions/chaincode-java/libs/`
- [ ] `cp netty-tcnative-boringssl-static-2.0.7.Final-linux-aarch_64.jar build/distributions/chaincode-java/libs/`
- [ ] `cp ../build.gradle build/distributions/chaincode-java/shim-src/`
- [ ] `cp ../settings.gradle build/distributions/chaincode-java/shim-src/`
- [ ] `cp ../gradlew build/distributions/chaincode-java/shim-src/`
- [ ] `cp ../gradlew.bat build/distributions/chaincode-java/shim-src/`
- [ ] `cp -r ../gradle build/distributions/chaincode-java/shim-src/`
- [ ] `cp -r ../fabric-chaincode-shim build/distributions/chaincode-java/shim-src/`
- [ ] `cp -r ../fabric-chaincode-protos build/distributions/chaincode-java/shim-src/`
- [ ] `cp ../build.gradle build/distributions/chaincode-java/example-src/`
- [ ] `cp ../settings.gradle build/distributions/chaincode-java/example-src/`
- [ ] `cp ../gradlew build/distributions/chaincode-java/example-src/`
- [ ] `cp ../gradlew.bat build/distributions/chaincode-java/example-src/`
- [ ] `cp -r ../gradle build/distributions/chaincode-java/example-src/`
- [ ] `cp -r ../fabric-chaincode-example-gradle build/distributions/chaincode-java/example-src/`
- [ ] `cp -r ../fabric-chaincode-example-maven build/distributions/chaincode-java/example-src/`
- [ ] `docker build . --no-cache`
The final output line of the docker build command will give you the identifier of the resulting docker image.
- [ ] `docker tag <identifier> hyperledger/fabric-javaenv:arm64-1.4.1`

After these quick and simple steps, you now have your own fabric-javaenv image!

**Comment by Tunstad** [comment]
Hi, 
This is great!

Yeah I will append this to [compiling.md](https://github.com/Tunstad/Hyperprov/blob/master/compiling.md) to have everything in one place.

Thanks for doing this and writing it down.
