### ISSUE TITLE
Inquiries regarding docker image reference

### ISSUE THREAD

**Issue by KimYC1223** [Tunstad/Hyperprov#16]
Hello, Tunstad.

I am a college student working on a blockchain project in an embedded system.

Your repository has been a great help for my project and I really appreciate it.

The information in this repository and the ReadMe file helped me in making my college graduation work.

That's why I'm almost finished with my work right now, and I'm uploading it to GIT.

So ... can I quote your Docker Image?

```
ptunstad / fabric-baseos: arm64-0.4.15
ptunstad / fabric-basejvm: arm64-0.4.15
ptunstad / fabric-baseimage: arm64-0.4.15
ptunstad / fabric-ccenv: arm64-1.4.1
ptunstad / fabric-peer: arm64-1.4.1
ptunstad / fabric-orderer: arm64-1.4.1
ptunstad / fabric-zookeeper: arm64-1.4.1
ptunstad / fabric-kafka: arm64-1.4.1
ptunstad / fabric-couchdb: arm64-1.4.1
ptunstad / fabric-tools: arm64-1.4.1
```

I want to create a wiki page of my work using the above image.

If you allow, I will write down your GIT repository address with appreciative words.

I can't find your email address, leaving an issue.

Thanks for reading.

**Comment by Tunstad** [comment]
Hi, i'm glad this repository was helpful. Quote the docker images and repository as you please, and if you need a text reference you can also use [this](https://munin.uit.no/handle/10037/15780). Good luck on finishing your graduation work, and if you need to reach me by email its: ´pettertunstad@gmail.com´.
