### ISSUE TITLE
Fatal Error: Runtime out of memory while making fabric base-image

### ISSUE THREAD

**Issue by mohit-kukreja** [Tunstad/Hyperprov#4]

**Comment by Tunstad** [comment]
Yeah, you may need to modify the line 
 -            Memory: 2147483648
to
+            Memory: 16777216
in core.yaml as mentioned in   [compiling.md](https://github.com/Tunstad/Hyperprov/blob/master/compiling.md) for building on Raspberry Pi.  


Also making a swap partition can be necessary if the devices run out of memory during build.  You can check for existing swap either with top or swapon --show. 1GB of swap should be more than enough, to create swap perform the following actions:

```
sudo fallocate -l 1G /swapfile
sudo dd if=/dev/zero of=/swapfile bs=1024 count=1048576
sudo chmod 600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile
sudo echo '/swapfile swap swap defaults 0 0' >> /etc/fstab
```
